project:
  type: website

website:
  title: "MSDS 597 PROJECT: NBA Data Analysis"
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: data cleaning
        file: data_cleaning/data_cleaning.ipynb
      - text: Visualization
        file: visualization/visual.ipynb
      - text: model
        file: model/Model.ipynb
      
      